// @generated by pi-protocol generate; DO NOT EDIT.
// contract-digest: sha256:1a2b70808ee2952cad65fd2f755f55975e2c6bd0df80c2cb2b42fe9fe26bfb0e
import type { ProtocolAgentExecutor, ProtocolHandler } from "@kybernetria/pi-protocol/core";

export const PROTOCOL_NODE_ID = "pi_toolkit" as const;
export const PROTOCOL_TARGETS = {
  schema: "pi_toolkit.schema",
  search: "pi_toolkit.search",
  add_tool: "pi_toolkit.add_tool",
  propose_assertion: "pi_toolkit.propose_assertion",
  list_tools: "pi_toolkit.list_tools",
} as const;

export type ProtocolProvideName = "schema" | "search" | "add_tool" | "propose_assertion" | "list_tools";
export type ProtocolBinding = ProtocolHandler | ProtocolAgentExecutor;
export type ProtocolBindings = {
  "schema": ProtocolBinding;
  "search": ProtocolBinding;
  "add_tool": ProtocolBinding;
  "propose_assertion": ProtocolBinding;
  "list_tools": ProtocolBinding;
};

export type SchemaInput = { communityId?: string; key?: string; limit?: number; operation: "list" | "show"; revision?: string; };
export type SchemaOutput = { communityId: string; operation: "list" | "show"; result: unknown; };
export type SearchInput = { communityId?: string; includePartial?: boolean; mandatory?: readonly ({ concept: string; conceptRevision?: string; op: "eq" | "ne" | "in" | "exists" | "gt" | "gte" | "lt" | "lte"; value?: unknown; })[]; optional?: readonly ({ concept: string; conceptRevision?: string; op: "eq" | "ne" | "in" | "exists" | "gt" | "gte" | "lt" | "lte"; value?: unknown; })[]; requirements?: readonly ({ concept: string; conceptRevision?: string; op: "eq" | "ne" | "in" | "exists" | "gt" | "gte" | "lt" | "lte"; required?: boolean; value?: unknown; })[]; tools?: readonly string[]; };
export type SearchOutput = { exact_count: number; results: readonly ({ match: "exact" | "partial"; name: string; requirements: readonly Record<string, never>[]; satisfied_requirements: number; tool: string; })[]; };
export type AddToolInput = { communityId?: string; description?: string; homepage?: string; idempotencyKey?: string; key: string; name: string; status?: "active" | "deprecated"; };
export type AddToolOutput = { communityId: string; idempotencyKey: string; result: { durable: true; operation_hash: string; state: Record<string, never>; status: "APPLIED"; }; };
export type ProposeAssertionInput = { asOf: string; assertionId?: string; assessment?: { evaluationDate: string; evaluatorType: string; rationale: string; rubric: string; rubricVersion: string; }; communityId?: string; concept: string; conceptRevision?: string; evidence: string; idempotencyKey?: string; source: string; tool: string; value: unknown; };
export type ProposeAssertionOutput = { assertionId: string; communityId: string; idempotencyKey: string; result: { assertion_id: string; durable: true; operation_hash: string; state: Record<string, never>; status: "APPLIED"; verification_state: "proposed"; }; };
export type ListToolsInput = { communityId?: string; limit?: number; offset?: number; };
export type ListToolsOutput = { communityId: string; hasMoreHint: boolean; limit: number; offset: number; tools: readonly ({ description: unknown; homepage: unknown; key: string; name: string; source_operation_hash: string; status: "active" | "deprecated"; })[]; };
